#!/bin/bash

echo "host $NODE down"

DIR_NAME=${DIR_NAME:-$(dirname $(readlink -f $0))}
DIR_NAME=${DIR_NAME:-"."}
echo "src dir: ${DIR_NAME}"
WORKING_DIR=$(pwd)
echo "working dir: ${WORKING_DIR}"

[ -f $WORKING_DIR/tinc-env ] && source $WORKING_DIR/tinc-env
source $DIR_NAME/tinc-env
[ -f $WORKING_DIR/hosts/$NODE-env ] && source $WORKING_DIR/hosts/$NODE-env
source $DIR_NAME/host-env

# delete proxy rule
iptables -t mangle -D $CHAIN_NAME -m mark --mark 0 -j MARK --set-mark $MARK_VALUE

# delete route table
ip rule del fwmark $MARK_VALUE table $ROUTE_TABLE
ip route flush table $ROUTE_TABLE

# reload dns
$DIR_NAME/reload-dns
