#!/bin/bash

VPN_GATEWAY=${VPN_GATEWAY:-${VPN_IP%.*}.1}
ROUTE_TABLE=${ROUTE_TABLE:-200}
MARK_VALUE=${MARK_VALUE:-${ROUTE_TABLE}}
echo "vpn gateway: ${VPN_GATEWAY}"
echo "route table: ${ROUTE_TABLE}"
echo "mark value: ${MARK_VALUE}"
