#!/bin/bash

echo "interface $INTERFACE up"

DIR_NAME=${DIR_NAME:-$(dirname $(readlink -f $0))}
DIR_NAME=${DIR_NAME:-"."}
echo "dir name: ${DIR_NAME}"

source $DIR_NAME/tinc-env

# create interface
ip link set $INTERFACE up
ip addr add $VPN_IP/24 dev $INTERFACE

# create bypass set with china list
echo "ipset name: ${SET_NAME}"
sed "s/^/add $SET_NAME /;1i create $SET_NAME hash:net family inet hashsize 4096 maxelem 65536" $DIR_NAME/chnroute.txt | ipset restore
echo "chnroute loaded"

# add bypass for lan
if [ $BYPASS_LAN -eq 1 ]; then
	ipset add $SET_NAME 10.0.0.0/8
	ipset add $SET_NAME 172.16.0.0/12
	ipset add $SET_NAME 192.168.0.0/16
fi

# add extra bypass
for bypass_addr in ${BYPASS[@]}; do
	ipset add $SET_NAME $bypass_addr
done

# enable nat
iptables -t nat -I POSTROUTING -o $INTERFACE -j MASQUERADE

# set rp_filter
echo 2 > /proc/sys/net/ipv4/conf/$INTERFACE/rp_filter
